export const ocorrencias = [
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'planejar tarefa 01 to tcc', idealizado: 'planejar tarefa 01 do tcc' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'diagnoticados', idealizado: 'diagnosticados' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'filaname', idealizado: 'filename' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'desição', idealizado: 'decisão' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'dia', idealizado: 'baia' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Contantedes', idealizado: 'constantes' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'desição', idealizado: 'decisão' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: '9', idealizado: '6' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: '458,68', idealizado: '456,49' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'incosistências', idealizado: 'inconsistências' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'reporitório', idealizado: 'repositório' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'tarbell', idealizado: 'tarball' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'dilexia', idealizado: 'dislexia' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'virgura', idealizado: 'virgula' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'seguito', idealizado: 'seguito' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'amg', idealizado: 'img' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Marlon', idealizado: 'Rodrigo' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'atuliazações', idealizado: 'atualizações' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'com ênfase na tonificação muscular foco e nos músculos', idealizado: 'com ênfase na tonificação muscular e foco nos músculos' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'conrtuir', idealizado: 'construir' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'porta 80 do contêiner', idealizado: 'porta 80 do host docontêiner' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'este contando', idealizado: 'está me contando' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'obrigado', idealizado: 'chegando' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'amanhar', idealizado: 'amanhã' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'cheira', idealizado: 'cheia' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'citato', idealizado: 'citado' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Plaejamento', idealizado: 'Planejamento' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Planjemanto', idealizado: 'Planejamento' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'dela', idealizado: 'tela' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'sinamliza', idealizado: 'sinalisa' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'reuniar', idealizado: 'reunir' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'acritica', idealizado: 'acrilica' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: '5384', idealizado: '3584' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'cabelo', idealizado: 'belo' },
    { tipo_interacao: 'entrada', tipo_acao: 'compreendi', realizado: 'não vi meu [...]', idealizado: 'renovei meu[...]' },
    { tipo_interacao: 'entrada', tipo_acao: 'compreendi', realizado: 'comeu a vizinha', idealizado: 'o meu lovezinho' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'teclado', idealizado: 'cmd' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'idalexia', idealizado: 'dislexia' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'para lização', idealizado: 'paralização' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'remover', idealizado: 'promover' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Tembém', idealizado: 'Também' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'AED', idealizado: 'EAD' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'teclar', idealizado: 'teclas' },
    { tipo_interacao: 'saida', tipo_acao: 'cantei', realizado: 'estaca', idealizado: 'escapa' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'deois', idealizado: 'dois' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'passar', idealizado: 'passado' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Occulare', idealizado: 'Ocullare' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Mercelo', idealizado: 'Marcelo' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'diferende', idealizado: 'diferente' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'am', idealizado: 'em' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'atc', idealizado: 'etc' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'começõ', idealizado: 'começou' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: 'alex', idealizado: 'axes' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'consideçãção', idealizado: 'consideração' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'probababilística', idealizado: 'probabilística' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'albebra', idealizado: 'algebra' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: '288', idealizado: '188' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'dereção', idealizado: 'direção' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'Histrograma', idealizado: 'Histograma' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'emplique', idealizado: 'explique' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'excrevi', idealizado: 'escrevi' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'excrevi', idealizado: 'escrevi' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'lihha', idealizado: 'linha' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'arrado', idealizado: 'errado' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'softaware', idealizado: 'software' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'explelhado', idealizado: 'espelhado' },
    { tipo_interacao: 'entrada', tipo_acao: 'li', realizado: '3738', idealizado: '7837' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'obssão', idealizado: 'omissão' },
    { tipo_interacao: 'saida', tipo_acao: 'escrevi', realizado: 'ErroFonologico', idealizado: 'Erro Fonológico' }]