FROM node:lts-alpine as builder

WORKDIR /fono

RUN apk add --no-cache nodejs-dev

COPY ./src ./src
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json

RUN npm install -g npm@10.5.2
RUN npm install --legacy-peer-deps

FROM node:lts-alpine

WORKDIR /fono

COPY --from=builder /fono/* ./

RUN npm install -g nodemon watchman
RUN npm install -g react-scripts

CMD npm run start